post_install() {
  xdg-icon-resource forceupdate --theme hicolor &> /dev/null
  update-desktop-database > /dev/null 2>&1
  
  getent group minetest &>/dev/null || groupadd --system minetest
  getent passwd minetest &>/dev/null || \
    useradd --system -g minetest -s /bin/false -d /var/lib/minetest minetest

  [[ ! -d var/lib/minetest ]] && install -d var/lib/minetest
  chown minetest:minetest var/lib/minetest
}

post_upgrade() {
  post_install
}

post_remove() {
  post_install
}
